provider: local
model: qwen2-0.5b-instruct
base_url: http://localhost:1234/v1
json_mode: false
use_grammar: false
max_tokens: 4000
temperature: 0.1
top_p: 0.9
concurrency: 1
rate_limit_rps: 1
retries: 3
retry_hint_template: prompts/retry_hint.txt
system_prompt: prompts/system.txt
fewshot_path: prompts/fewshot.jsonl
schema_path: schema/mathir.schema.json
input_csv: tasks.csv
output_dir: out_json
log_level: DEBUG
seed: 17